In [1]:
with open("../docs/schema.sql", "r") as f:
    schema = f.read()

print(schema)

-- =====================================================
-- Air Quality Dataset Schema (3NF)
-- =====================================================

-- =========================
-- 1. STATION TABLE
-- =========================
CREATE TABLE IF NOT EXISTS t_station (
    station_id INT PRIMARY KEY,
    station_name VARCHAR(255),
    latitude DOUBLE,
    longitude DOUBLE
);

-- =========================
-- 2. TIME TABLE
-- =========================
CREATE TABLE IF NOT EXISTS t_time (
    time_id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE,
    hour INT,
    UNIQUE (date, hour)
);

-- =========================
-- 3. MEASUREMENT TABLE
-- =========================
CREATE TABLE IF NOT EXISTS t_measurement (
    measurement_id INT AUTO_INCREMENT PRIMARY KEY,
    station_id INT NOT NULL,
    time_id INT NOT NULL,

    -- Pollutants
    SO2 DOUBLE,
    NO DOUBLE,
    NO2 DOUBLE,
    CO DOUBLE,
    PM10 DOUBLE,
    O3 DOUBLE,
    PM25 DOUBLE,

    -- Wind
    wind_direction DOUBLE,
    wind_speed DOUBLE,

    -- Weather
    temperature DOUBLE,
    humidity DOUBLE,
    pressure DOUBLE,
    solar_radiation DOUBLE,
    rain DOUBLE,

    -- Additional chemicals
    BEN DOUBLE,
    TOL DOUBLE,
    MXIL DOUBLE,

    -- Foreign Keys
    CONSTRAINT fk_station FOREIGN KEY (station_id)
        REFERENCES t_station(station_id),

    CONSTRAINT fk_time FOREIGN KEY (time_id)
        REFERENCES t_time(time_id)
);

In [2]:
with open("../docs/schema.sql", "r") as f:
    schema = f.read()

print(schema)

-- =====================================================
-- Air Quality Dataset Schema (3NF)
-- =====================================================

-- =========================
-- 1. STATION TABLE
-- =========================
CREATE TABLE IF NOT EXISTS t_station (
    station_id INT PRIMARY KEY,
    station_name VARCHAR(255),
    latitude DOUBLE,
    longitude DOUBLE
);

-- =========================
-- 2. TIME TABLE
-- =========================
CREATE TABLE IF NOT EXISTS t_time (
    time_id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE,
    hour INT,
    UNIQUE (date, hour)
);

-- =========================
-- 3. MEASUREMENT TABLE
-- =========================
CREATE TABLE IF NOT EXISTS t_measurement (
    measurement_id INT AUTO_INCREMENT PRIMARY KEY,
    station_id INT NOT NULL,
    time_id INT NOT NULL,

    -- Pollutants
    SO2 DOUBLE,
    NO DOUBLE,
    NO2 DOUBLE,
    CO DOUBLE,
    PM10 DOUBLE,
    O3 DOUBLE,
    PM25 DOUBLE,

    -- Wind
    wind_direction DOUBLE,
    wind_speed DOUBLE,

    -- Weather
    temperature DOUBLE,
    humidity DOUBLE,
    pressure DOUBLE,
    solar_radiation DOUBLE,
    rain DOUBLE,

    -- Additional chemicals
    BEN DOUBLE,
    TOL DOUBLE,
    MXIL DOUBLE,

    -- Foreign Keys
    CONSTRAINT fk_station FOREIGN KEY (station_id)
        REFERENCES t_station(station_id),

    CONSTRAINT fk_time FOREIGN KEY (time_id)
        REFERENCES t_time(time_id)
);

In [ ]:
import os
import pandas as pd
from getpass import getpass

from dbrepo.RestClient import RestClient
from dbrepo.api.dto import UpdateColumn

client = RestClient(
    endpoint="https://test.dbrepo.tuwien.ac.at",
    username=" ",
    password=getpass("DBRepo password: ")
)

print("DBRepo client initialized.")

DBRepo client initialized.

In [ ]:
DB_ID = " "

db = client.get_database(DB_ID)

print("Database:", db.name)
print("Tables:", len(db.tables))
print("Views:", len(db.views))
print("Accesses:", db.accesses)

for table in db.tables:
    print("-", table.name)

Database: data_stew_grp22_air_quality
Tables: 3
Views: 3
Accesses: [DatabaseAccess(type=<AccessType.WRITE_ALL: 'write_all'>, user=UserBrief(username='12450741', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None))]
- t_measurement
- t_time
- t_station

In [ ]:
TABLE_IDS = {
    "t_measurement": "",
    "t_time": "",
    "t_station": "",
}

COLUMN_IDS = {
    ("t_station", "latitude"): "",
    ("t_station", "longitude"): "",

    ("t_measurement", "SO2"): "",
    ("t_measurement", "NO"): "",
    ("t_measurement", "NO2"): "",
    ("t_measurement", "CO"): "",
    ("t_measurement", "PM10"): "",
    ("t_measurement", "O3"): "",
    ("t_measurement", "PM25"): "",

    ("t_measurement", "wind_direction"): "",
    ("t_measurement", "wind_speed"): "",
    ("t_measurement", "temperature"): "",
    ("t_measurement", "humidity"): "",
    ("t_measurement", "pressure"): "",
    ("t_measurement", "solar_radiation"): "",
    ("t_measurement", "rain"): "",

    ("t_measurement", "BEN"): "",
    ("t_measurement", "TOL"): "",
    ("t_measurement", "MXIL"): "",
}

In [6]:
semantic_concept_mappings = [
    # Station metadata
    {
        "table": "t_station",
        "column": "station_id",
        "ontology": "DBpedia",
        "concept_label": "Monitoring station",
        "concept_uri": "http://dbpedia.org/resource/Monitoring_station"
    },
    {
        "table": "t_station",
        "column": "station_name",
        "ontology": "DBpedia",
        "concept_label": "Monitoring station",
        "concept_uri": "http://dbpedia.org/resource/Monitoring_station"
    },
    {
        "table": "t_station",
        "column": "latitude",
        "ontology": "DBpedia",
        "concept_label": "Latitude",
        "concept_uri": "http://dbpedia.org/resource/Latitude"
    },
    {
        "table": "t_station",
        "column": "longitude",
        "ontology": "DBpedia",
        "concept_label": "Longitude",
        "concept_uri": "http://dbpedia.org/resource/Longitude"
    },

    # Time metadata
    {
        "table": "t_time",
        "column": "time_id",
        "ontology": "DBpedia",
        "concept_label": "Time",
        "concept_uri": "http://dbpedia.org/resource/Time"
    },
    {
        "table": "t_time",
        "column": "date",
        "ontology": "DBpedia",
        "concept_label": "Calendar date",
        "concept_uri": "http://dbpedia.org/resource/Calendar_date"
    },
    {
        "table": "t_time",
        "column": "hour",
        "ontology": "DBpedia",
        "concept_label": "Hour",
        "concept_uri": "http://dbpedia.org/resource/Hour"
    },

    # Measurement identifiers / foreign keys
    {
        "table": "t_measurement",
        "column": "measurement_id",
        "ontology": "DBpedia",
        "concept_label": "Measurement",
        "concept_uri": "http://dbpedia.org/resource/Measurement"
    },
    {
        "table": "t_measurement",
        "column": "station_id",
        "ontology": "DBpedia",
        "concept_label": "Monitoring station",
        "concept_uri": "http://dbpedia.org/resource/Monitoring_station"
    },
    {
        "table": "t_measurement",
        "column": "time_id",
        "ontology": "DBpedia",
        "concept_label": "Time",
        "concept_uri": "http://dbpedia.org/resource/Time"
    },

    # Air pollutants / chemical compounds
    {
        "table": "t_measurement",
        "column": "SO2",
        "ontology": "DBpedia",
        "concept_label": "Sulfur dioxide",
        "concept_uri": "http://dbpedia.org/resource/Sulfur_dioxide"
    },
    {
        "table": "t_measurement",
        "column": "NO",
        "ontology": "DBpedia",
        "concept_label": "Nitric oxide",
        "concept_uri": "http://dbpedia.org/resource/Nitric_oxide"
    },
    {
        "table": "t_measurement",
        "column": "NO2",
        "ontology": "DBpedia",
        "concept_label": "Nitrogen dioxide",
        "concept_uri": "http://dbpedia.org/resource/Nitrogen_dioxide"
    },
    {
        "table": "t_measurement",
        "column": "CO",
        "ontology": "DBpedia",
        "concept_label": "Carbon monoxide",
        "concept_uri": "http://dbpedia.org/resource/Carbon_monoxide"
    },
    {
        "table": "t_measurement",
        "column": "PM10",
        "ontology": "DBpedia",
        "concept_label": "Particulates",
        "concept_uri": "http://dbpedia.org/resource/Particulates"
    },
    {
        "table": "t_measurement",
        "column": "PM25",
        "ontology": "DBpedia",
        "concept_label": "Particulates",
        "concept_uri": "http://dbpedia.org/resource/Particulates"
    },
    {
        "table": "t_measurement",
        "column": "O3",
        "ontology": "DBpedia",
        "concept_label": "Ozone",
        "concept_uri": "http://dbpedia.org/resource/Ozone"
    },
    {
        "table": "t_measurement",
        "column": "BEN",
        "ontology": "DBpedia",
        "concept_label": "Benzene",
        "concept_uri": "http://dbpedia.org/resource/Benzene"
    },
    {
        "table": "t_measurement",
        "column": "TOL",
        "ontology": "DBpedia",
        "concept_label": "Toluene",
        "concept_uri": "http://dbpedia.org/resource/Toluene"
    },
    {
        "table": "t_measurement",
        "column": "MXIL",
        "ontology": "DBpedia",
        "concept_label": "Xylene",
        "concept_uri": "http://dbpedia.org/resource/Xylene"
    },

    # Physical / environmental quantities, OM2
    {
        "table": "t_measurement",
        "column": "wind_direction",
        "ontology": "OM2",
        "concept_label": "Angle",
        "concept_uri": "http://www.ontology-of-units-of-measure.org/resource/om-2/Angle"
    },
    {
        "table": "t_measurement",
        "column": "wind_speed",
        "ontology": "OM2",
        "concept_label": "Speed",
        "concept_uri": "http://www.ontology-of-units-of-measure.org/resource/om-2/Speed"
    },
    {
        "table": "t_measurement",
        "column": "temperature",
        "ontology": "OM2",
        "concept_label": "Temperature",
        "concept_uri": "http://www.ontology-of-units-of-measure.org/resource/om-2/Temperature"
    },
    {
        "table": "t_measurement",
        "column": "humidity",
        "ontology": "OM2",
        "concept_label": "Relative humidity",
        "concept_uri": "http://www.ontology-of-units-of-measure.org/resource/om-2/RelativeHumidity"
    },
    {
        "table": "t_measurement",
        "column": "pressure",
        "ontology": "OM2",
        "concept_label": "Pressure",
        "concept_uri": "http://www.ontology-of-units-of-measure.org/resource/om-2/Pressure"
    },
    {
        "table": "t_measurement",
        "column": "solar_radiation",
        "ontology": "OM2",
        "concept_label": "Irradiance",
        "concept_uri": "http://www.ontology-of-units-of-measure.org/resource/om-2/Irradiance"
    },
    {
        "table": "t_measurement",
        "column": "rain",
        "ontology": "DBpedia",
        "concept_label": "Rain",
        "concept_uri": "http://dbpedia.org/resource/Rain"
    },
]

semantic_concept_df = pd.DataFrame(semantic_concept_mappings)

semantic_concept_df

,table,column,ontology,concept_label,concept_uri
0,t_station,station_id,DBpedia,Monitoring station,http://dbpedia.org/resource/Monitoring_station
1,t_station,station_name,DBpedia,Monitoring station,http://dbpedia.org/resource/Monitoring_station
2,t_station,latitude,DBpedia,Latitude,http://dbpedia.org/resource/Latitude
3,t_station,longitude,DBpedia,Longitude,http://dbpedia.org/resource/Longitude
4,t_time,time_id,DBpedia,Time,http://dbpedia.org/resource/Time
5,t_time,date,DBpedia,Calendar date,http://dbpedia.org/resource/Calendar_date
6,t_time,hour,DBpedia,Hour,http://dbpedia.org/resource/Hour
7,t_measurement,measurement_id,DBpedia,Measurement,http://dbpedia.org/resource/Measurement
8,t_measurement,station_id,DBpedia,Monitoring station,http://dbpedia.org/resource/Monitoring_station
9,t_measurement,time_id,DBpedia,Time,http://dbpedia.org/resource/Time
10,t_measurement,SO2,DBpedia,Sulfur dioxide,http://dbpedia.org/resource/Sulfur_dioxide
11,t_measurement,NO,DBpedia,Nitric oxide,http://dbpedia.org/resource/Nitric_oxide
12,t_measurement,NO2,DBpedia,Nitrogen dioxide,http://dbpedia.org/resource/Nitrogen_dioxide
13,t_measurement,CO,DBpedia,Carbon monoxide,http://dbpedia.org/resource/Carbon_monoxide
14,t_measurement,PM10,DBpedia,Particulates,http://dbpedia.org/resource/Particulates
15,t_measurement,PM25,DBpedia,Particulates,http://dbpedia.org/resource/Particulates
16,t_measurement,O3,DBpedia,Ozone,http://dbpedia.org/resource/Ozone
17,t_measurement,BEN,DBpedia,Benzene,http://dbpedia.org/resource/Benzene
18,t_measurement,TOL,DBpedia,Toluene,http://dbpedia.org/resource/Toluene
19,t_measurement,MXIL,DBpedia,Xylene,http://dbpedia.org/resource/Xylene
20,t_measurement,wind_direction,OM2,Angle,http://www.ontology-of-units-of-measure.org/re...
21,t_measurement,wind_speed,OM2,Speed,http://www.ontology-of-units-of-measure.org/re...
22,t_measurement,temperature,OM2,Temperature,http://www.ontology-of-units-of-measure.org/re...
23,t_measurement,humidity,OM2,Relative humidity,http://www.ontology-of-units-of-measure.org/re...
24,t_measurement,pressure,OM2,Pressure,http://www.ontology-of-units-of-measure.org/re...
25,t_measurement,solar_radiation,OM2,Irradiance,http://www.ontology-of-units-of-measure.org/re...
26,t_measurement,rain,DBpedia,Rain,http://dbpedia.org/resource/Rain

In [7]:
check_rows = []

for _, mapping in semantic_concept_df.iterrows():
    table_id = TABLE_IDS[mapping["table"]]
    column_id = COLUMN_IDS[(mapping["table"], mapping["column"])]

    table_obj = client.get_table(DB_ID, table_id)

    col_obj = next(
        c for c in table_obj.columns
        if c.id == column_id
    )

    current_uri = getattr(col_obj, "concept_uri", None)

    check_rows.append({
        "table": mapping["table"],
        "column": mapping["column"],
        "expected_uri": mapping["concept_uri"],
        "current_uri": current_uri,
        "already_updated": current_uri == mapping["concept_uri"]
    })

semantic_check_before_df = pd.DataFrame(check_rows)

semantic_check_before_df

,table,column,expected_uri,current_uri,already_updated
0,t_station,station_id,http://dbpedia.org/resource/Monitoring_station,http://dbpedia.org/resource/Monitoring_station,True
1,t_station,station_name,http://dbpedia.org/resource/Monitoring_station,http://dbpedia.org/resource/Monitoring_station,True
2,t_station,latitude,http://dbpedia.org/resource/Latitude,http://dbpedia.org/resource/Latitude,True
3,t_station,longitude,http://dbpedia.org/resource/Longitude,http://dbpedia.org/resource/Longitude,True
4,t_time,time_id,http://dbpedia.org/resource/Time,http://dbpedia.org/resource/Time,True
5,t_time,date,http://dbpedia.org/resource/Calendar_date,http://dbpedia.org/resource/Calendar_date,True
6,t_time,hour,http://dbpedia.org/resource/Hour,http://dbpedia.org/resource/Hour,True
7,t_measurement,measurement_id,http://dbpedia.org/resource/Measurement,http://dbpedia.org/resource/Measurement,True
8,t_measurement,station_id,http://dbpedia.org/resource/Monitoring_station,http://dbpedia.org/resource/Monitoring_station,True
9,t_measurement,time_id,http://dbpedia.org/resource/Time,http://dbpedia.org/resource/Time,True
10,t_measurement,SO2,http://dbpedia.org/resource/Sulfur_dioxide,http://dbpedia.org/resource/Sulfur_dioxide,True
11,t_measurement,NO,http://dbpedia.org/resource/Nitric_oxide,http://dbpedia.org/resource/Nitric_oxide,True
12,t_measurement,NO2,http://dbpedia.org/resource/Nitrogen_dioxide,http://dbpedia.org/resource/Nitrogen_dioxide,True
13,t_measurement,CO,http://dbpedia.org/resource/Carbon_monoxide,http://dbpedia.org/resource/Carbon_monoxide,True
14,t_measurement,PM10,http://dbpedia.org/resource/Particulates,http://dbpedia.org/resource/Particulates,True
15,t_measurement,PM25,http://dbpedia.org/resource/Particulates,http://dbpedia.org/resource/Particulates,True
16,t_measurement,O3,http://dbpedia.org/resource/Ozone,http://dbpedia.org/resource/Ozone,True
17,t_measurement,BEN,http://dbpedia.org/resource/Benzene,http://dbpedia.org/resource/Benzene,True
18,t_measurement,TOL,http://dbpedia.org/resource/Toluene,http://dbpedia.org/resource/Toluene,True
19,t_measurement,MXIL,http://dbpedia.org/resource/Xylene,http://dbpedia.org/resource/Xylene,True
20,t_measurement,wind_direction,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
21,t_measurement,wind_speed,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
22,t_measurement,temperature,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
23,t_measurement,humidity,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
24,t_measurement,pressure,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
25,t_measurement,solar_radiation,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
26,t_measurement,rain,http://dbpedia.org/resource/Rain,http://dbpedia.org/resource/Rain,True

In [8]:
semantic_upload_results = []

for _, row in semantic_check_before_df.iterrows():

    if row["already_updated"] == True:
        semantic_upload_results.append({
            "table": row["table"],
            "column": row["column"],
            "concept_uri": row["expected_uri"],
            "status": "already_updated",
            "error": None
        })
        continue

    try:
        table_id = TABLE_IDS[row["table"]]
        column_id = COLUMN_IDS[(row["table"], row["column"])]

        client.update_table_column(
            database_id=DB_ID,
            table_id=table_id,
            column_id=column_id,
            concept_uri=row["expected_uri"]
        )

        semantic_upload_results.append({
            "table": row["table"],
            "column": row["column"],
            "concept_uri": row["expected_uri"],
            "status": "success",
            "error": None
        })

    except Exception as e:
        semantic_upload_results.append({
            "table": row["table"],
            "column": row["column"],
            "concept_uri": row["expected_uri"],
            "status": "failed",
            "error": repr(e)
        })

semantic_upload_df = pd.DataFrame(semantic_upload_results)

semantic_upload_df

,table,column,concept_uri,status,error
0,t_station,station_id,http://dbpedia.org/resource/Monitoring_station,already_updated,None
1,t_station,station_name,http://dbpedia.org/resource/Monitoring_station,already_updated,None
2,t_station,latitude,http://dbpedia.org/resource/Latitude,already_updated,None
3,t_station,longitude,http://dbpedia.org/resource/Longitude,already_updated,None
4,t_time,time_id,http://dbpedia.org/resource/Time,already_updated,None
5,t_time,date,http://dbpedia.org/resource/Calendar_date,already_updated,None
6,t_time,hour,http://dbpedia.org/resource/Hour,already_updated,None
7,t_measurement,measurement_id,http://dbpedia.org/resource/Measurement,already_updated,None
8,t_measurement,station_id,http://dbpedia.org/resource/Monitoring_station,already_updated,None
9,t_measurement,time_id,http://dbpedia.org/resource/Time,already_updated,None
10,t_measurement,SO2,http://dbpedia.org/resource/Sulfur_dioxide,already_updated,None
11,t_measurement,NO,http://dbpedia.org/resource/Nitric_oxide,already_updated,None
12,t_measurement,NO2,http://dbpedia.org/resource/Nitrogen_dioxide,already_updated,None
13,t_measurement,CO,http://dbpedia.org/resource/Carbon_monoxide,already_updated,None
14,t_measurement,PM10,http://dbpedia.org/resource/Particulates,already_updated,None
15,t_measurement,PM25,http://dbpedia.org/resource/Particulates,already_updated,None
16,t_measurement,O3,http://dbpedia.org/resource/Ozone,already_updated,None
17,t_measurement,BEN,http://dbpedia.org/resource/Benzene,already_updated,None
18,t_measurement,TOL,http://dbpedia.org/resource/Toluene,already_updated,None
19,t_measurement,MXIL,http://dbpedia.org/resource/Xylene,already_updated,None
20,t_measurement,wind_direction,http://www.ontology-of-units-of-measure.org/re...,already_updated,None
21,t_measurement,wind_speed,http://www.ontology-of-units-of-measure.org/re...,already_updated,None
22,t_measurement,temperature,http://www.ontology-of-units-of-measure.org/re...,already_updated,None
23,t_measurement,humidity,http://www.ontology-of-units-of-measure.org/re...,already_updated,None
24,t_measurement,pressure,http://www.ontology-of-units-of-measure.org/re...,already_updated,None
25,t_measurement,solar_radiation,http://www.ontology-of-units-of-measure.org/re...,already_updated,None
26,t_measurement,rain,http://dbpedia.org/resource/Rain,already_updated,None

In [9]:
semantic_upload_df["status"].value_counts()

status
already_updated    27
Name: count, dtype: int64

In [10]:
final_check_rows = []

for _, mapping in semantic_concept_df.iterrows():
    table_id = TABLE_IDS[mapping["table"]]
    column_id = COLUMN_IDS[(mapping["table"], mapping["column"])]

    table_obj = client.get_table(DB_ID, table_id)

    col_obj = next(
        c for c in table_obj.columns
        if c.id == column_id
    )

    current_uri = getattr(col_obj, "concept_uri", None)

    final_check_rows.append({
        "table": mapping["table"],
        "column": mapping["column"],
        "expected_uri": mapping["concept_uri"],
        "current_uri": current_uri,
        "updated_correctly": current_uri == mapping["concept_uri"]
    })

semantic_final_check_df = pd.DataFrame(final_check_rows)

semantic_final_check_df

,table,column,expected_uri,current_uri,updated_correctly
0,t_station,station_id,http://dbpedia.org/resource/Monitoring_station,http://dbpedia.org/resource/Monitoring_station,True
1,t_station,station_name,http://dbpedia.org/resource/Monitoring_station,http://dbpedia.org/resource/Monitoring_station,True
2,t_station,latitude,http://dbpedia.org/resource/Latitude,http://dbpedia.org/resource/Latitude,True
3,t_station,longitude,http://dbpedia.org/resource/Longitude,http://dbpedia.org/resource/Longitude,True
4,t_time,time_id,http://dbpedia.org/resource/Time,http://dbpedia.org/resource/Time,True
5,t_time,date,http://dbpedia.org/resource/Calendar_date,http://dbpedia.org/resource/Calendar_date,True
6,t_time,hour,http://dbpedia.org/resource/Hour,http://dbpedia.org/resource/Hour,True
7,t_measurement,measurement_id,http://dbpedia.org/resource/Measurement,http://dbpedia.org/resource/Measurement,True
8,t_measurement,station_id,http://dbpedia.org/resource/Monitoring_station,http://dbpedia.org/resource/Monitoring_station,True
9,t_measurement,time_id,http://dbpedia.org/resource/Time,http://dbpedia.org/resource/Time,True
10,t_measurement,SO2,http://dbpedia.org/resource/Sulfur_dioxide,http://dbpedia.org/resource/Sulfur_dioxide,True
11,t_measurement,NO,http://dbpedia.org/resource/Nitric_oxide,http://dbpedia.org/resource/Nitric_oxide,True
12,t_measurement,NO2,http://dbpedia.org/resource/Nitrogen_dioxide,http://dbpedia.org/resource/Nitrogen_dioxide,True
13,t_measurement,CO,http://dbpedia.org/resource/Carbon_monoxide,http://dbpedia.org/resource/Carbon_monoxide,True
14,t_measurement,PM10,http://dbpedia.org/resource/Particulates,http://dbpedia.org/resource/Particulates,True
15,t_measurement,PM25,http://dbpedia.org/resource/Particulates,http://dbpedia.org/resource/Particulates,True
16,t_measurement,O3,http://dbpedia.org/resource/Ozone,http://dbpedia.org/resource/Ozone,True
17,t_measurement,BEN,http://dbpedia.org/resource/Benzene,http://dbpedia.org/resource/Benzene,True
18,t_measurement,TOL,http://dbpedia.org/resource/Toluene,http://dbpedia.org/resource/Toluene,True
19,t_measurement,MXIL,http://dbpedia.org/resource/Xylene,http://dbpedia.org/resource/Xylene,True
20,t_measurement,wind_direction,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
21,t_measurement,wind_speed,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
22,t_measurement,temperature,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
23,t_measurement,humidity,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
24,t_measurement,pressure,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
25,t_measurement,solar_radiation,http://www.ontology-of-units-of-measure.org/re...,http://www.ontology-of-units-of-measure.org/re...,True
26,t_measurement,rain,http://dbpedia.org/resource/Rain,http://dbpedia.org/resource/Rain,True